-- AI视频生成任务表
CREATE TABLE IF NOT EXISTS zrws_video_task (
    task_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
    task_no VARCHAR(64) NOT NULL COMMENT '任务编号',
    task_name VARCHAR(255) DEFAULT NULL COMMENT '任务名称',
    provider VARCHAR(32) DEFAULT NULL COMMENT '视频生成提供商',
    generation_mode VARCHAR(16) DEFAULT NULL COMMENT '生成模式: TEXT_TO_VIDEO/IMAGE_TO_VIDEO',
    prompt TEXT COMMENT '提示词（中文）',
    prompt_en TEXT COMMENT '英文提示词',
    negative_prompt TEXT COMMENT '负面提示词',
    reference_image_url VARCHAR(500) DEFAULT NULL COMMENT '参考图片URL',
    duration INT DEFAULT 5 COMMENT '视频时长（秒）',
    width INT DEFAULT 720 COMMENT '视频宽度',
    height INT DEFAULT 1280 COMMENT '视频高度',
    fps INT DEFAULT 24 COMMENT '帧率',
    model_name VARCHAR(64) DEFAULT NULL COMMENT '模型名称',
    style_preset VARCHAR(64) DEFAULT NULL COMMENT '风格预设',
    provider_task_id VARCHAR(128) DEFAULT NULL COMMENT '提供商侧任务ID',
    video_url VARCHAR(500) DEFAULT NULL COMMENT '生成的视频URL',
    video_path VARCHAR(500) DEFAULT NULL COMMENT '视频本地存储路径',
    file_name VARCHAR(255) DEFAULT NULL COMMENT '视频文件名',
    file_size BIGINT DEFAULT 0 COMMENT '文件大小（字节）',
    cover_url VARCHAR(500) DEFAULT NULL COMMENT '封面图URL',
    status VARCHAR(16) DEFAULT 'PENDING' COMMENT '状态',
    progress INT DEFAULT 0 COMMENT '进度百分比 0-100',
    operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
    operator_name VARCHAR(64) DEFAULT NULL COMMENT '操作人姓名',
    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
    start_time DATETIME DEFAULT NULL COMMENT '开始生成时间',
    end_time DATETIME DEFAULT NULL COMMENT '完成时间',
    error_message TEXT COMMENT '错误信息',
    retry_count INT DEFAULT 0 COMMENT '重试次数',
    extra_params TEXT COMMENT '扩展参数JSON',
    callback_url VARCHAR(500) DEFAULT NULL COMMENT '回调URL',
    is_deleted TINYINT DEFAULT 0 COMMENT '逻辑删除',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (task_id),
    UNIQUE KEY uk_task_no (task_no),
    KEY idx_provider_task_id (provider_task_id),
    KEY idx_status (status),
    KEY idx_operator_id (operator_id),
    KEY idx_created_time (created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI视频生成任务表';
